# Generated by Django 6.0.3 on 2026-04-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_discription', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to='images')),
                ('product_discount', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g. 10 for 10%)', max_digits=5)),
            ],
        ),
    ]
