# Write a Python program to demonstrate string slicing.
str = "Python Programing"
print(f"\"{str}\" Slice [6:]: ", str[6:])
print("\n---------------------------------------------------------")
print(f"\"{str}\" Slice [:8]: ", str[:8])
print("\n---------------------------------------------------------")
print(f"\"{str}\" Slice [::-1]: ", str[::-1])
print("\n---------------------------------------------------------")
print(f"\"{str}\" Slice [7:14]: ", str[7:14])
print("\n---------------------------------------------------------")
print(f"\"{str}\" Slice [-1]: ", str[-1])


# Write a Python program that manipulates and prints strings using various string methods
str_name = input("Enter Your String : ")
print(len(str))
print("\n---------------------------------------------------------")
print(str_name.lower())
print("\n---------------------------------------------------------")
print(str_name.upper())
print("\n---------------------------------------------------------")
print(str_name.capitalize())
print("\n---------------------------------------------------------")
print(str_name.strip())
print("\n---------------------------------------------------------")
print(str_name.title())
print("\n---------------------------------------------------------")
print(str_name.find("P"))
print("\n---------------------------------------------------------")
print(str_name.replace("p","p"))
print("\n---------------------------------------------------------")
print(str_name.startswith("p"))
print("\n---------------------------------------------------------")
print(str_name.endswith("on"))
print("\n---------------------------------------------------------")
print(str_name.join("L"))
print("\n---------------------------------------------------------")
print(str_name.isdigit())
print("\n---------------------------------------------------------")
print(str_name.isalpha())
print("\n---------------------------------------------------------")
print(str_name.isalnum())
print("\n---------------------------------------------------------")
print(str_name.zfill(19))